export const CHAR_TAB = 9; // \t
export const CHAR_LINE_FEED = 10; // \n
export const CHAR_CARRIAGE_RETURN = 13; // \r
export const CHAR_SPACE = 32; // space
export const CHAR_EXCLAMATION = 33; // !
export const CHAR_OPEN_PAREN = 40; // (
export const CHAR_CLOSE_PAREN = 41; // )
export const CHAR_DASH = 45; // -
export const CHAR_SLASH = 47; // /
export const CHAR_ZERO = 48; // 0
export const CHAR_NINE = 57; // 9
export const CHAR_COLON = 58; // :
export const CHAR_AT = 64; // @
export const CHAR_UPPER_A = 65; // A
export const CHAR_UPPER_Z = 90; // Z
export const CHAR_OPEN_BRACKET = 91; // [
export const CHAR_CLOSE_BRACKET = 93; // ]
export const CHAR_UNDERSCORE = 95; // _
export const CHAR_LOWER_A = 97; // a
export const CHAR_LOWER_N = 110; // n
export const CHAR_LOWER_S = 115; // s
export const CHAR_LOWER_Z = 122; // z
export const CHAR_LINE_SEPARATOR = 8232; // line separator
export const CHAR_PARAGRAPH_SEPARATOR = 8233; // paragraph separator
