export const MERGE_CACHE_CAPACITY = 2048;
export const MERGE_CACHE_CAPACITY_MAX = 8192;

export const DOORKEEPER_SLOTS = 8192;

export const MAX_CONFLICT_KEYS = 16384;

export const PREPARED_PART_CACHE_SIZE = 2048;

export const INTERN_TABLE_INITIAL_SLOTS = 2048;
export const INTERN_TABLE_MAX_SLOTS = 16384;
export const INTERN_TABLE_HARD_MAX_SLOTS = 32768;

export const JSC_STARTSWITH_VERIFY_MIN_LENGTH = 12;

export const RESULT_INTERN_SLOTS = 1024;

export const ARGUMENT_CACHE_BUCKET_ENTRIES = 96;
export const ARGUMENT_CACHE_ROTATION_SLOTS = 2048;
export const ARGUMENT_CACHE_SEEN_ONCE_CAPACITY = 500;

export const ARGUMENT_CACHE_PREDICTION_SLOTS = 2048;

export const CALL_SITE_MEMO_ROWS = 4;
export const CALL_SITE_MEMO_ROW_ARG_SLOTS = 12;

export const CVA_MEMO_ROWS = 8;
export const CVA_MEMO_MAX_VALUE_SLOTS = 16;

export const SPACE_CHARACTER = " ";
export const OPEN_BRACKET_CHARACTER = "[";
export const COLON_CHARACTER = ":";

export const SLICED_REPRESENTATION_MIN_LENGTH = 13;

export const INITIAL_CLAIM_SLOTS = 256;
export const INITIAL_TOKEN_SLOTS = 64;
export const INITIAL_CONFLICT_POOL_SLOTS = 1024;
export const INITIAL_PREPARED_PART_SLOTS = 16;

export const FNV_SIGNED_OFFSET_BASIS = -2128831035;
export const FNV_PRIME = 16777619;

export const FINGERPRINT_LENGTH_FACTOR = 61;
export const FINGERPRINT_FIRST_CHARACTER_FACTOR = 131;
export const FINGERPRINT_LAST_CHARACTER_FACTOR = 31;
export const FINGERPRINT_MIDDLE_CHARACTER_FACTOR = 7;
